version: '3.8'

services:
  pdf-unlocker:
    image: hetaozhen/z-pdf-unlocker:latest
    container_name: z_pdf_unlocker
    ports:
      - "53535:53535"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - LAN_PASSWORD=your_secure_password # 可选，局域网共享模式下的访问密码保护
